# Generated by Django 2.0 on 2018-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20180627_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
