# Generated by Django 2.0 on 2018-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20180627_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='copyquotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotes',
            name='shareFacebook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotes',
            name='shareInstagram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotes',
            name='shareWhatsapp',
            field=models.IntegerField(default=0),
        ),
    ]
